# Basic configuration for Pseudocode Translator
# This uses the default Qwen model

llm:
  # Model selection
  model_type: qwen  # Default model
  model_path: ./models
  model_file: qwen-7b-q4_k_m.gguf
  
  # Model parameters
  n_ctx: 2048
  n_batch: 512
  n_threads: 4
  n_gpu_layers: 0  # Set to > 0 if you have GPU support
  
  # Generation parameters
  temperature: 0.3
  top_p: 0.9
  top_k: 40
  repeat_penalty: 1.1
  max_tokens: 1024
  
  # Performance settings
  cache_enabled: true
  cache_size_mb: 500
  cache_ttl_hours: 24
  
  # Model management
  max_loaded_models: 1
  model_ttl_minutes: 60
  auto_download: false
  
  # Validation
  timeout_seconds: 30
  validation_level: strict  # strict, normal, or lenient

# Translation settings
max_context_length: 2048
preserve_comments: true
preserve_docstrings: true
auto_import_common: true

# Code style preferences
indent_size: 4
use_type_hints: true
max_line_length: 88

# Validation settings
validate_imports: true
check_undefined_vars: true
allow_unsafe_operations: false

# GUI preferences
gui_theme: dark
gui_font_size: 12
syntax_highlighting: true